language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck doxygen graphviz lcov qt5-qmake qtbase5-dev #rubygems
 #- gem install lcoveralls

before_script:
  - qmake -qt=qt5

script:
  - cppcheck --error-exitcode=1 --quiet .
  - make
  - make check

after_success:
  - make -C test coverage
 #- lcoveralls --retry-count 5
